logging:
  level:
    org.springframework.jdbc.core: trace
    org:
      springframework:
        security: info

spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            scope: read:public_repo
  datasource:
    password: admin
    username: admin
    url: jdbc:postgresql://localhost:5432/jorken